tasks:
  - before: >
      composer self-update --1
      wget -qOdatabase-setup.sh https://codejudge-starter-repo-artifacts.s3.ap-south-1.amazonaws.com/gitpod/backend/php/gitpod-setup.sh &&
      chmod 0755 database-setup.sh &&
      bash database-setup.sh 7.1
    init: composer update && composer install && npm i && php artisan key:generate
    command: php artisan serve --host=127.0.0.1 --port=8080
ports:
  - port: 8080
    name: "Backend Server"
    onOpen: open-browser
    visibility: public
  - port: 3306
    name: "MySQL Server"
    onOpen: ignore
    visibility: public
  - port: 27017
    name: "MongoDB Server"
    onOpen: ignore
    visibility: public
vscode:
  extensions:
    - felixfbecker.php-debug
    - bmewburn.vscode-intelephense-client
